name: Deploy
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Install netlify globally
        run: npm install -g netlify-cli@latest
      - name: Build the project
        run: netlify build
      - name: Deploying
        run: netlify deploy --prod
